### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by Freethetan**
Added brake lines

Added some unordered list

Just to show what is Pull Request or short PR

### CODE REVIEW

**Comment by Freethetan** [comment]
I think it has to be improved a bit more
Add span tag too

**Comment by Hala1286** [comment]
I think it has to be improved a bit more.
Add hyperlinks, photos etc.

**Comment by Hadeel-123** [comment]
I think it you need add order list

**Comment by Freethetan** [comment]
Okay
For now I will do as is

**Pull request merged**
